// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPXCHYw5Pcgeunxl5mMxOb4O6K5SgqGhI',
    appId: '1:804517591810:web:f044022911f3bc72f3e01b',
    messagingSenderId: '804517591810',
    projectId: 'debtdude-1b2e9',
    authDomain: 'debtdude-1b2e9.firebaseapp.com',
    storageBucket: 'debtdude-1b2e9.firebasestorage.app',
    measurementId: 'G-82GYXYSG7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzUWoNbs2hi_NYsZtF5MZS3rAMKrCKuzY',
    appId: '1:804517591810:android:ab196b1d168fa9b9f3e01b',
    messagingSenderId: '804517591810',
    projectId: 'debtdude-1b2e9',
    storageBucket: 'debtdude-1b2e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWZPO7q58aNzuGXI6C0qrFCpWL0ZbCwo',
    appId: '1:804517591810:ios:7563ba1565b48265f3e01b',
    messagingSenderId: '804517591810',
    projectId: 'debtdude-1b2e9',
    storageBucket: 'debtdude-1b2e9.firebasestorage.app',
    iosBundleId: 'com.example.debtdude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWZPO7q58aNzuGXI6C0qrFCpWL0ZbCwo',
    appId: '1:804517591810:ios:7563ba1565b48265f3e01b',
    messagingSenderId: '804517591810',
    projectId: 'debtdude-1b2e9',
    storageBucket: 'debtdude-1b2e9.firebasestorage.app',
    iosBundleId: 'com.example.debtdude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPXCHYw5Pcgeunxl5mMxOb4O6K5SgqGhI',
    appId: '1:804517591810:web:46dccc7a359c03fff3e01b',
    messagingSenderId: '804517591810',
    projectId: 'debtdude-1b2e9',
    authDomain: 'debtdude-1b2e9.firebaseapp.com',
    storageBucket: 'debtdude-1b2e9.firebasestorage.app',
    measurementId: 'G-ZBNF01JVTH',
  );

}