// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZqCNcucDsfb2VgDuY9Y65Gp2BgwqxREg',
    appId: '1:460205960176:web:4a406e734a5a60ca320b35',
    messagingSenderId: '460205960176',
    projectId: 'debtdude-3b56e',
    authDomain: 'debtdude-3b56e.firebaseapp.com',
    storageBucket: 'debtdude-3b56e.firebasestorage.app',
    measurementId: 'G-8XTXM93D5K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlklmxogMIUrB8bFUAx4FE5Q-fbYRbOo',
    appId: '1:460205960176:android:55c1bf9ab73390b8320b35',
    messagingSenderId: '460205960176',
    projectId: 'debtdude-3b56e',
    storageBucket: 'debtdude-3b56e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZwP9_dJ_1JRwyrHnsNMXSouSyJcS0pc',
    appId: '1:460205960176:ios:9b48bb7f16d49fec320b35',
    messagingSenderId: '460205960176',
    projectId: 'debtdude-3b56e',
    storageBucket: 'debtdude-3b56e.firebasestorage.app',
    iosBundleId: 'com.example.debtdude',
  );
}
