// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAajGY3mlV5U4WoEW_UCPuHhJPGCUjxXhY',
    appId: '1:197549008094:web:0d974dbee2c08c4a1b8e4f',
    messagingSenderId: '197549008094',
    projectId: 'debtdude-c9eef',
    authDomain: 'debtdude-c9eef.firebaseapp.com',
    storageBucket: 'debtdude-c9eef.firebasestorage.app',
    measurementId: 'G-L4SD5H6V0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBthUyBEaydAE1uYUBpo4V9nNGEru7jngU',
    appId: '1:197549008094:android:135ecbb8d35c8f131b8e4f',
    messagingSenderId: '197549008094',
    projectId: 'debtdude-c9eef',
    storageBucket: 'debtdude-c9eef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIQmQmMqMmeyTYPmTYFhHKlhYhW63BZ0I',
    appId: '1:197549008094:ios:8a1f18d6bbce4e751b8e4f',
    messagingSenderId: '197549008094',
    projectId: 'debtdude-c9eef',
    storageBucket: 'debtdude-c9eef.firebasestorage.app',
    iosBundleId: 'com.example.debtdude',
  );
}
