name: Flutter Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Allows manual triggering

env:
  FLUTTER_VERSION: '3.32.6' # Use stable Flutter version

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        cache: true

    - name: Verify Flutter installation
      run: |
        flutter --version
        flutter doctor

    - name: Get dependencies
      run: flutter pub get

    # - name: Run tests
    #   run: flutter test

    - name: Build Android APK
      run: |
        flutter build apk --release --no-tree-shake-icons
      env:
        FLUTTER_BUILD_MODE: release

    - name: Build Android App Bundle
      run: |
        flutter build appbundle --release --no-tree-shake-icons
      env:
        FLUTTER_BUILD_MODE: release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: debtdude-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

    - name: Upload App Bundle
      uses: actions/upload-artifact@v4
      with:
        name: debtdude-appbundle
        path: build/app/outputs/bundle/release/app-release.aab
        retention-days: 30

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          Automatic build triggered by ${{ github.event.head_commit.message }}
          
          Build includes:
          - Android APK
          - Android App Bundle
          - Built with --no-tree-shake-icons flag
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}